### ISSUE TITLE
Compatibility of Arduino Mega ADK

### ISSUE THREAD

**Issue by varunkumar** [webusb/arduino#38]
Is this library compatible with Arduino Mega ADK board? https://www.arduino.cc/en/Main/ArduinoBoardMegaADK?from=Main.ArduinoBoardADK

**Comment by jpliew** [comment]
@varunkumar the MEGA board has a ATmega8U2 chip bridging the USB. The flash and ram in this chip is probably too low to run this library.

**Comment by xander777** [comment]
I tried to use my chinees copy of MEGA 2560 with console demo app and it didn't work.
maybe someone knows how to fix it or what min parameters of board should be for work with WebUSB?

**Comment by reillyeon** [comment]
The UNO and MEGA are built differently from the boards which are supported. Instead of the USB port being directly connected to the microcontroller on which your sketch (and the WebUSB library) runs there is an additional chip which acts as a USB to serial converter and connects to one of the UART pins on the main microcontroller. This means that in order to get WebUSB support on the device you need to reprogram this chip as well and this is currently unsupported.

**Comment by varunkumar** [comment]
Thanks for the explanation
