### ISSUE TITLE
Not getting webusb notification in Chrome

### ISSUE THREAD

**Issue by sandeepks1** [webusb/arduino#42]
I am very new to web USB,To experiment for how exactly webusb works

I bought one Arduino board. Folowed the steps in https://github.com/webusb/arduino Loaded up sketch.ino and program it to my device. 
Here my problem is still am not getting below notification 
![usbnotifications](https://user-images.githubusercontent.com/7323348/34207646-611dca18-e5b1-11e7-97a8-0f4e2de1bfe9.png)

i bought this device from 
https://www.amazon.in/REES52-Arduino-Leonardo-R3/dp/B01KI9LQTQ?tag=googinhydr18418-21

**Comment by reillyeon** [comment]
You have not specified what operating system you are using but since the screenshot is from Chrome OS I am going to assume that is where you are. The issue is likely that the device is still not reporting a bcdUSB (USB protocol version) of 0x0210 (2.1). Please double-check that you have modified the headers as instructed.

If you are on Windows then this notification has been disabled due to instabilities in Chrome's code on Windows. Work to fix this is ongoing.

**Comment by sandeepks1** [comment]
I am using windows 10  OS,How to enable this notification in chrome (Version 63.0.3239)

**Comment by reillyeon** [comment]
You cannot currently enable the notification on Windows. It will be re-enabled when the issues it triggers are fixed. The current status is described in [README.md](https://github.com/webusb/arduino/blob/gh-pages/README.md).
