### ISSUE TITLE
Chrome Version and Android

### ISSUE THREAD

**Issue by puttley** [webusb/arduino#70]
Hello - I have a webUSB device that works perfectly with the latest versions of Chrome on Win 10 and Mac OS. However, the newest version of Chrome for Android will no longer work...earlier versions did.

When attempting to connect using an Android device, I get a SecurityError: Access denied message. My device will show up in the device selection window, but when I select it and attempt to connect I get a NotFoundError: No device selected.

Is there a known issue with Android and the latest version for Chrome 77.0.3865.116 ?

**Comment by reillyeon** [comment]
This is a known issue with Chrome 77 and has been fixed in Chrome 78 ([issue 1009362](https://bugs.chromium.org/p/chromium/issues/detail?id=1009362)). You can verify this issue has been fixed by installing [Chrome Beta](https://play.google.com/store/apps/details?id=com.chrome.beta) from the Google Play Store. According to [the schedule](https://chromiumdash.appspot.com/schedule) Chrome 78 should be released to stable-channel users shortly.

**Comment by puttley** [comment]
Thanks for the prompt reply. I downloaded and installed Chrome Beta 78.0.3904.62. The webUSB device appears in the device list window, but once I select it and attempt to connect, Chrome crashes and closes. Still, no issues with the latest versions of Chrome on Win 10, Mac and Chromebook - only Android.

**Comment by reillyeon** [comment]
I've filed an issue internally to track this. Thanks for checking.

**Comment by puttley** [comment]
Very much appreciated,  thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by puttley** [comment]
Has there been an update on this issue?

**Comment by reillyeon** [comment]
The issue has been fixed in Chrome 78.0.3904.90 and is rolling out to stable-channel now.

**Comment by puttley** [comment]
Good news. Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
